apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e654svwd0-nodejs
  janus-idp.io/tekton: e654svwd0-nodejs
  backstage.io/kubernetes-id: e654svwd0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e654svwd0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
